# Generated by Django 6.0.6 on 2026-09-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_seat_options_alter_booking_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
